spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api

async:
  executor:
    thread-core-pool-size: 10
    thread-max-pool-size: 50
    thread-queue-capacity: 100

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
